# Chap9. 통계와 수학적 기능을 위한 Numpy

9.1 Numpy의 설치

9.2 Numpy의 기초

In [3]:
###Numpy 배열
#array; numpy형식으로 변환
#shape; numpy배열의 객체가 지원해주는 속성(차원,원소 확인)
import numpy as np
x= np.array([1,3,5])
print(x.mean())
print(x.shape)

y= np.array([[1,2,3],[2,3,4]])
print(y.shape)

3.0
(3,)
(2, 3)


In [5]:
#reshape; 원하는 배열 모양으로 변환
x= np.array([1,3,5,7,9,11]).reshape(3,2)
print(x)

#ones; 배열 모양 지정-> 1의 값으로 채움
y= np.ones([3,4])
print(y)

[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
x= np.array([[1,3,5],[2,4,6]])
print(x[1])
print(x[1].mean())
print(x.mean())
print(x.shape)

[2 4 6]
4.0
3.5
(2, 3)
12


In [12]:
###Numpy 배열의 슬라이싱
list1 = [[1,11],[2,12],[3,13]]
print(list1[1][1])

list1= [[1,11],[2,12],[3,13]]
print(list1[:][1]) #원하는 형식X
#print(list1[:, 1]) error

import numpy as np
list1= [[1,11],[2,12],[3,13]]
np_ary= np.array(list1)
print(np_ary[:,1])

list2= [[1,11],[2,12],[3,13]]
#print(np.array(list2[:,1])) error
print(np.array(list2[:][0])) #원하는 형식X

12
[11 12 13]
[ 1 11]


In [16]:
###Numpy를 이용한 연산
import math
math.sqrt(2)
#math.sqrt([2,3,4])

import numpy as np
np.sqrt([2,3,4])

a= np.arange(15)
print(a)
a= np.arange(15).reshape(3,5)
print(a)
print(a[1,1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
6


In [17]:
###제로 벡터와 제로 행렬
import numpy as np
zero_vector= np.zeros(3) #1차원배열
zero_matrix= np.zeros((4,3)) #2차원배열
print(zero_vector)
print(zero_matrix)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
zero_vector

array([0., 0., 0.])

In [19]:
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
my_array= np.zeros(15).reshape(3,5)
my_array+= 4
my_array

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [28]:
###전치행렬
import numpy as np
ary= np.array([[1,2],[3,4]])
print(ary.transpose())

[[1 3]
 [2 4]]


In [32]:
x=[1,2,3]
y=[4,5,6]
z=x+y
print(z)

x=np.array([1,2,3])
y=np.array([4,5,6])
z=x+y
print(z)
print(x*y)

[1, 2, 3, 4, 5, 6]
[5 7 9]
[ 4 10 18]


In [34]:
s=[1,2,3]
#print(s+1)

s=np.array([1,2,3])
print(s+1)

[2 3 4]


In [35]:
x= np.array([4,8,12])
y= np.array([2,4,6])
print(x/y)

[2. 2. 2.]


In [36]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(x[1])
print(x[:,1])
print(x[:,1]+y[:,1])

[4 5 6]
[2 5 8]
[ 5 11 17]


In [37]:
a= np.array([10,20,30,40,50,60,70])
i= [1,3,5]
print(a[i])

[20 40 60]


In [38]:
a= np.array([10,20,30,40,50,60,70])
b= a[1:6:2]
print('b: ',b)
b[1]= 10
print('b: ',b)
print('a: ',a)

b:  [20 40 60]
b:  [20 10 60]
a:  [10 20 30 10 50 60 70]


In [39]:
a= np.array([10,20,30,40,50,60,70])
b= np.array(a[1:6:2])
print('b: ',b)
b[1]= 10
print('b: ',b)
print('a: ',a)

b:  [20 40 60]
b:  [20 10 60]
a:  [10 20 30 40 50 60 70]


In [21]:
###불리언
a= np.array([10,20,30,40,50,60,70])
b= a>50
print(b)

ary= np.random.rand(5)
print(ary)
print(np.all(ary >= 0.3))
print(np.any(ary > 0.7))

[False False False False False  True  True]
[0.90132191 0.77594173 0.57126414 0.83013698 0.79415814]
True
True


In [23]:
import numpy as np
height= np.array([173, 168, 171, 189, 179])
weight= np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi= ((weight/height)**2)*100
print(bmi)
print(bmi>20)

[14.29102209 12.41723356 13.83317944 21.87665519 14.73015823]
[False False False  True False]


In [ ]:
###등간격 나누기

In [27]:
import numpy as np
print(np.linspace(0,12,4))
print(np.linspace(0,12,4, retstep=True))
print(np.linspace(0,12,4, endpoint=False))

print(np.logspace(np.log10(10),np.log10(100),5))
print(np.logspace(1,2,5))

[ 0.  4.  8. 12.]
(array([ 0.,  4.,  8., 12.]), 4.0)
[0. 3. 6. 9.]
[ 10.          17.7827941   31.6227766   56.23413252 100.        ]
[ 10.          17.7827941   31.6227766   56.23413252 100.        ]
